production:
  adapter: <%= ENV['DB_ADAPTER'].to_s.empty? ? "postgresql" : ENV['DB_ADAPTER'] %>
  database: <%= ENV['DB_DATABASE'].to_s.empty? ? "redmine" : ENV['DB_DATABASE'] %>
  host: <%= ENV['DB_HOST'].to_s.empty? ? "172.17.42.1" : ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'].to_s.empty? ? "redmine" : ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3

